language: rust
rust:
- stable
- nightly

script:
  - rustup component add rustfmt
  - cargo fmt -- --check
  - rustup component add clippy
  - cargo clippy --all-features --all-targets -- -D warnings 
  - cargo build
  - cargo test

  - cd nocopy_macro
  - cargo fmt -- --check
  - cargo clippy --all-features --all-targets -- -D warnings 
  - cargo build
  - cargo test
