[package]
name = "nocopy_macro"
version = "0.1.0"
authors = ["John Baublitz <john.m.baublitz@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
quote = "0.6.4"
syn = "0.14.5"
proc-macro2 = "0.4.9"
